recipes/recipes/main/urls.py
from django.urls import path

from recipes.main.views import show_home, create_recipe, delete_recipe, edit_recipe, show_recipe_details

urlpatterns=(
    path('', show_home, name='index'),
    path('create/', create_recipe, name='create recipe'),
    path('edit/<int:pk>/', edit_recipe, name='edit recipe'),
    path('delete/<int:pk>/', delete_recipe, name='delete recipe'),
    path('details/<int:pk>/', show_recipe_details, name='recipe details'),
)

recipes/recipes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.main.urls')),
]

recipes/recipes/main/models.py
from django.db import models


class Recipe(models.Model):
    TITLE_MAX_LENGTH = 30
    INGREDIENTS_MAX_LENGTH = 250

    title = models.CharField(
        max_length=TITLE_MAX_LENGTH,
    )

    image_url = models.URLField()

    description = models.TextField(
        null=True,
        blank=True,
    )

    ingredients = models.CharField(
        max_length=INGREDIENTS_MAX_LENGTH,
        null=True,
        blank=True
    )

    time = models.IntegerField()

recipes/recipes/main/forms.py
from django import forms
from django.core.exceptions import ValidationError


def ingredients_validator(value):
    if " " in value:
        raise ValidationError("Ingredients must be separated only by comma!")


class RecipeCreateForm(forms.Form):
    title = forms.CharField(
        max_length=30,
    )

    image_url = forms.URLField(
        label='Image URL'
    )

    description = forms.CharField(widget=forms.Textarea)

    ingredients = forms.CharField(
        max_length=250,
        validators=(
            ingredients_validator,
        )
    )

    time = forms.IntegerField(
        label='Time(Minutes)'
    )


class RecipeEditForm(forms.Form):
    title = forms.CharField(
        max_length=30,
    )

    image_url = forms.URLField(
        label='Image URL'
    )

    description = forms.CharField(widget=forms.Textarea)

    ingredients = forms.CharField(
        max_length=250,
        validators=(
        )
    )

    time = forms.IntegerField(
        label='Time(Minutes)'
    )


class RecipeDeleteForm(forms.Form):
    title = forms.CharField(
        max_length=30,
        disabled=True,
    )

    image_url = forms.URLField(
        label='Image URL',
        disabled=True,
    )

    description = forms.CharField(
        widget=forms.Textarea,
        disabled=True,
    )

    ingredients = forms.CharField(
        max_length=250,
        disabled=True,
        validators=(
            ingredients_validator,
        )
    )

    time = forms.IntegerField(
        label='Time(Minutes)',
        disabled=True,
    )

recipes/recipes/main/views.py
from django import forms
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect

from recipes.main.forms import RecipeCreateForm, RecipeEditForm, RecipeDeleteForm
from recipes.main.helpers import get_recipe
from recipes.main.models import Recipe


def show_home(request):
    recipes = get_recipe()
    context = {
        'recipes': recipes,
    }
    return render(request, 'index.html', context)


def create_recipe(request):
    if request.method == 'POST':
        recipe_form = RecipeCreateForm(request.POST)

        if recipe_form.is_valid():
            recipe = Recipe(
                title=recipe_form.cleaned_data['title'],
                image_url=recipe_form.cleaned_data['image_url'],
                description=recipe_form.cleaned_data['description'],
                ingredients=recipe_form.cleaned_data['ingredients'],
                time=recipe_form.cleaned_data['time'],
            )
            recipe.save()
            return redirect('index')
    else:
        recipe_form = RecipeCreateForm()

    context = {
        'recipe_form': recipe_form,
    }
    return render(request, 'create.html', context)


def edit_recipe(request, pk):
    recipe_to_edit=Recipe.objects.get(pk=pk)

    if request.method == 'POST':
        recipe_form = RecipeEditForm(request.POST)

        if recipe_form.is_valid():
            recipe_to_edit.title = recipe_form.cleaned_data['title']
            recipe_to_edit.image_url=recipe_form.cleaned_data['image_url']
            recipe_to_edit.description=recipe_form.cleaned_data['description']
            recipe_to_edit.ingredients=recipe_form.cleaned_data['ingredients']
            recipe_to_edit.time=recipe_form.cleaned_data['time']
            recipe_to_edit.save()
            return redirect('index')
    else:
        recipe_form = RecipeEditForm(initial=recipe_to_edit.__dict__)

    context = {
        'recipe_edit_form': recipe_form,
        'recipe_to_edit': recipe_to_edit,
    }
    return render(request, 'edit.html', context)


def delete_recipe(request, pk):
    recipe_to_delete = Recipe.objects.get(pk=pk)

    if request.method == 'POST':
        recipe_form = RecipeDeleteForm(request.POST)
        recipe_to_delete.delete()
        return redirect('index')
    else:
        recipe_form = RecipeDeleteForm(initial=recipe_to_delete.__dict__)

    context = {
        'recipe_delete_form': recipe_form,
        'recipe_to_delete': recipe_to_delete,
    }
    return render(request, 'delete.html', context)


def show_recipe_details(request, pk):
    recipe_for_details = Recipe.objects.get(pk=pk)
    context={
        'recipe_for_details': recipe_for_details,
        'ingredients_list': recipe_for_details.ingredients.split(','),
    }
    return render(request, 'details.html', context)

recipes/recipes/main/templates/create.html
{% extends 'base.html' %}
{% block page_content %}

    <h1>Create Recipe</h1>
    <div class="items-container">
        <div class="item">
            <form method="post" action="{% url 'create recipe' %}">
                {% csrf_token %}
                {{ recipe_form }}
                <input type="submit" value="Create">
            </form>
            {#        <form method="POST">#}
            {#            {% csrf_token %}#}
            {#            <label for="title">Title</label>#}
            {#            <input type="text" name="title" maxlength="30" required="" id="id_title">#}
            {#            <label for="imageURL">Image URL</label>#}
            {#            <input type="url" name="image_url" maxlength="200" required="" id="id_image_url">#}
            {#            <label for="description">Description</label>#}
            {#            <textarea name="description" cols="40" rows="10" required="" id="id_description"></textarea>#}
            {#            <label for="ingredients">Ingredients</label>#}
            {#            <input type="text" name="ingredients" maxlength="250" required="" id="id_ingredients">#}
            {#            <label for="time">Time (Minutes)</label>#}
            {#            <input type="number" name="time" required="" id="id_time">#}
            {#            <input type="submit" value="Create">#}
            {#        </form>#}
        </div>
    </div>

{% endblock %}

recipes/recipes/main/templates/delete.html
{% extends 'base.html' %}
{% block page_content %}

<h1>Delete Recipe</h1>
<div class="items-container">
    <div class="item">
        <form method="post" action="{% url 'delete recipe' recipe_to_delete.id %}">
            {% csrf_token %}
            {{ recipe_delete_form }}
            <input type="submit" class="button delete" value="Delete">
        </form>
{#        <form method="POST">#}
{#            <label for="title">Title</label>#}
{#            <input type="text" name="title" value="Homemade Chicken Soup" maxlength="30" disabled="" required="" id="id_title">#}
{#            <label for="imageURL">Image URL</label>#}
{#            <input type="url" name="image_url" value="https://i.ytimg.com/vi/o91gT73mQhg/maxresdefault.jpg" maxlength="200" disabled="" required="" id="id_image_url">#}
{#            <label for="description">Description</label>#}
{#            <textarea name="description" cols="40" rows="10" disabled="" required="" id="id_description">Put the chicken, carrots, celery and onion in a large soup pot and cover with cold water. Heat and simmer, uncovered, until the chicken meat falls off of the bones (skim off foam every so often).#}
{#Take everything out of the pot. Strain the broth. Pick the meat off of the bones and chop the carrots, celery and onion. Season the broth with salt, pepper and chicken bouillon to taste, if desired. Return the chicken, carrots, celery and onion to the pot, stir together, and serve.</textarea>#}
{#            <label for="ingredients">Ingredients</label>#}
{#            <input type="text" name="ingredients" value="1 (3 pound) whole chicken, 4 medium (blank)s carrots halved, 4 stalks celery halved, 1 large onion halved, water to cover, salt and pepper to taste, 1 teaspoon chicken bouillon granules" maxlength="250" disabled="" required="" id="id_ingredients">#}
{#            <label for="time">Time (Minutes)</label>#}
{#            <input type="number" name="time" value="30" disabled="" required="" id="id_time">#}
{#            <input type="submit" class="button delete" value="Delete">#}
{#        </form>#}
    </div>
</div>
{% endblock %}

recipes/recipes/main/templates/details.html
{% extends 'base.html' %}
{% block page_content %}
        
<h1>Recipe Details</h1>
        <div class="items-container">
            <div class="item">
                <h2>{{ recipe_for_details.title }}</h2>
                <img class="detail-img" src="{{ recipe_for_details.image_url }}" alt="recipe-image">
                <div class="time">
                    <img src="../../../static/images/clock.png" alt="pic">
                    <p>30min</p>
                </div>
                <h3>Ingredients</h3>
                <ul>
                    {% for ingredient in ingredients_list %}
                        <li>{{ ingredient }}</li>
                    {% endfor %}
                </ul>
                <h3>How to prepare?</h3>
                <div class="recipe-info-full">
                    {{ recipe_for_details.description }}
                </div>
                <div class="buttons-container">
                    <a class="button edit" href="{% url 'edit recipe' recipe_for_details.id %}">Edit</a>
                    <a class="button delete" href="{% url 'delete recipe' recipe_for_details.id %}">Delete</a>
                </div>
            </div>
        </div>

{% endblock %}

recipes/recipes/main/templates/edit.html
{% extends 'base.html' %}
{% block page_content %}

    <h1>Edit Recipe</h1>
    <div class="items-container">
        <div class="item">
            <form method="post" action="{% url 'edit recipe' recipe_to_edit.id %}">
                {% csrf_token %}
                {{ recipe_edit_form }}
                <input type="submit" class="button edit" value="Edit">
            </form>
            {#            <label for="title">Title</label>#}
            {#            <input type="text" name="title" value="Homemade Chicken Soup" maxlength="30" required="" id="id_title">#}
            {#            <label for="imageURL">Image URL</label>#}
            {#            <input type="url" name="image_url" value="https://i.ytimg.com/vi/o91gT73mQhg/maxresdefault.jpg" maxlength="200"  required="" id="id_image_url">#}
            {#            <label for="description">Description</label>#}
            {#            <textarea name="description" cols="40" rows="10"  required="" id="id_description">Put the chicken, carrots, celery and onion in a large soup pot and cover with cold water. Heat and simmer, uncovered, until the chicken meat falls off of the bones (skim off foam every so often).#}
            {#Take everything out of the pot. Strain the broth. Pick the meat off of the bones and chop the carrots, celery and onion. Season the broth with salt, pepper and chicken bouillon to taste, if desired. Return the chicken, carrots, celery and onion to the pot, stir together, and serve.</textarea>#}
            {#            <label for="ingredients">Ingredients</label>#}
            {#            <input type="text" name="ingredients" value="1 (3 pound) whole chicken, 4 medium (blank)s carrots halved, 4 stalks celery halved, 1 large onion halved, water to cover, salt and pepper to taste, 1 teaspoon chicken bouillon granules" maxlength="250"  required="" id="id_ingredients">#}
            {#            <label for="time">Time (Minutes)</label>#}
            {#            <input type="number" name="time" value="30" required="" id="id_time">#}
            {#            <input type="submit" class="button edit" value="Edit">#}
        </div>
    </div>
{% endblock %}

recipes/recipes/main/templates/index.html
{% extends 'base.html' %}
{% block page_content %}

    <h1>My Recipes</h1>
    {% if not recipes %}
        <h2>There are no recipes.</h2>
    {% else %}
        <div class="items-container">
        {% for recipe in recipes %}
            <div class="item">
                <h2>{{ recipe.title }}</h2>
                <img class="detail-img" src="{{ recipe.image_url }}" alt="recipe-image">
                <div class="recipe-info">
                    {{ recipe.description }}
                </div>
                <div class="buttons-container">
                    <a class="button detail" href="{% url 'recipe details' recipe.id %}">Details</a>
                    <a class="button edit" href="{% url 'edit recipe' recipe.id %}">Edit</a>
                    <a class="button delete" href="{% url 'delete recipe' recipe.id %}">Delete</a>
                </div>
            </div>
        {% endfor %}
    {% endif %}

    </div>
{% endblock %}

recipes/templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <title>Recipes</title>
</head>

<body>

<nav>
    <ul>
        <img src="../static/images/chef.png" alt="chef">
        <li class="title"><a href="/">Recipes</a></li>
        <li><a href="{% url 'create recipe' %}">Add Recipe</a></li>
    </ul>
</nav>
    <div class="container">
        {% block page_content %}
        {% endblock %}
    </div>


</body>

</html>